Corregir los siguientes errores:
Parser.cs(457,37): error CS0029: Cannot implicitly convert type `Falak.Node' to `Falak.Token'
Parser.cs(533,20): error CS0103: The name `expr2' does not exist in the current context
Parser.cs(556,21): error CS1950: The best overloaded collection initalizer method `Falak.Node.Add(Falak.Node)' has some invalid arguments
Node.cs(42,21): (Location of the symbol related to previous error)
Parser.cs(556,21): error CS1503: Argument `#1' cannot convert `Falak.Token' expression to type `Falak.Node'
Parser.cs(571,17): warning CS1717: Assignment made to same variable; did you mean to assign something else?
Parser.cs(689,13): error CS0163: Control cannot fall through from one case label `case 34:' to another
Parser.cs(692,13): warning CS0162: Unreachable code detected
Compilation failed: 6 error(s), 2 warnings
Makefile:25: recipe for target 'falak.exe' failed
make: *** [falak.exe] Error 1